apiVersion: v2
name: redis-exporter-wrapper
description: Wrapper chart for Redis Exporter
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: prometheus-redis-exporter
    version: ">=6.12.0"
    repository: https://prometheus-community.github.io/helm-charts
