apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-logback
data:
  logback.xml: |
    <configuration scan="true" scanPeriod="60 seconds">
      <jmxConfigurator />

      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>level=%level ts=%d{ISO8601} logger=%logger{36} thread=%thread msg="%msg"%n</pattern>
        </encoder>
      </appender>

      <root level="INFO">
        <appender-ref ref="STDOUT" />
      </root>

      <logger name="org.apache.cassandra" level="INFO"/>
      <logger name="com.thinkaurelius.thrift" level="ERROR"/>
    </configuration>
