{{- if .Values.registerJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-primary
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation,HookSucceeded
    "argocd.argoproj.io/sync-options": Replace=true
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      
      containers:
      - name: register
        image: {{ default .Values.registerJob.image.registry .Values.global.image.registry }}/curlimages/curl:{{ .Values.registerJob.image.tag }}
        command:
          - /bin/sh
          - -uc
          - |
            echo "Registering Cassandra..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            echo "Sending registration request..."
            http_code=$(curl -sS -o /tmp/response.txt -w "%{http_code}" \
              -X POST "http://openframe-management.microservices.svc.cluster.local:8095/v1/tools/cassandra-primary" \
              -H "Content-Type: application/json" \
              --connect-timeout 5 \
              --max-time 20 \
              -d '{
                "tool": {
                  "id": "cassandra-primary",
                  "toolType": "CASSANDRA",
                  "name": "Cassandra Database",
                  "description": "Cassandra Distributed Database",
                  "toolUrls": [
                    {
                      "url": "cassandra://cassandra.datasources.svc.cluster.local",
                      "port": "9042",
                      "type": "DATABASE"
                    }
                  ],
                  "category": "NoSQL Database",
                  "platformCategory": "OpenFrame Datasource",
                  "enabled": true,
                  "credentials": {},
                  "layer": "Datasource",
                  "layerOrder": 3,
                  "layerColor": "#616161",
                  "metricsPath": "/metrics",
                  "healthCheckEndpoint": "/health",
                  "healthCheckInterval": 30,
                  "connectionTimeout": 5000,
                  "readTimeout": 5000,
                  "allowedEndpoints": ["/api/v1/*","/metrics"],
                  "debeziumConnectors": []
                }
              }' \
              --retry 5 \
              --retry-delay 2 \
              --retry-all-errors)

            echo "----- Response body -----"
            cat /tmp/response.txt || true
            echo "-------------------------"

            [ -z "$http_code" ] || [ "$http_code" != 200 ] && { echo "Cassandra Registration failed..."; exit 1; }
            echo "Cassandra Registration complete."
{{- end }}
