environment: dev

deployment:
  oss:
    enabled: true    
    repository:
      profile: dev
  saas:
    enabled: false

registry:
  docker:
    server: https://index.docker.io/v1/
    username: ""
    password: ""
    email: ""

registerJob:
  enabled: true
servicemonitor:
  enabled: true
 
image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-stream
  tag: latest