apiVersion: v2
name: ingress-nginx-wrapper
description: Wrapper chart for Ingress Nginx
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: ingress-nginx
    version: ">=4.13.0"
    repository: https://kubernetes.github.io/ingress-nginx
