apiVersion: v2
name: telepresence-wrapper
description: Wrapper chart for Telepresence OSS
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: telepresence-oss
    version: ">=2.23.6"
    repository: oci://ghcr.io/flamingo-stack/registry/helm-charts
