registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"

telepresence-oss:
  image:
    registry: ghcr.io/flamingo-stack/registry/telepresenceio
    name: tel2
    tag: "2.25.1"

  hooks:
    busybox:
      registry: ghcr.io/flamingo-stack/registry
      image: busybox
      tag: "1.36"

    curl:
      registry: ghcr.io/flamingo-stack/registry
      image: curlimages/curl
      tag: "8.9.1"

deployment:
  saas:
    enabled: true
    ingress:
      localhost:
        enabled: true   # Enable localhost ingress with nginx for SaaS
      gcp:
        enabled: false
        gkeSecurityGroup: "gke-security-groups@flamingo.cx"
