environment: dev

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"

telepresence-oss:
  image:
    registry: ghcr.io/flamingo-stack/registry
    name: telepresenceio/tel2
    tag: "2.25.1"

deployment:
  saas:
    enabled: true
    ingress:
      localhost:
        enabled: true   # Enable localhost ingress with nginx for SaaS
      gcp:
        enabled: false
        gkeSecurityGroup: "gke-security-groups@flamingo.cx"
