registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"

initContainer:
  image:
    registry: ghcr.io/flamingo-stack/registry
    tag: "8.9.1"

image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-external-api
  tag: latest

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

podAnnotations:
  loki.grafana.com/scrape: "true"
  prometheus.io/scrape: "true"
  prometheus.io/port: "8093"
  prometheus.io/path: "/management/v1/prometheus"
