apiVersion: v2
name: kafka-ui-wrapper
description: Wrapper chart for Kafka UI
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: kafka-ui
    version: ">=1.4.12"
    repository: https://kafbat.github.io/helm-charts
