apiVersion: v2
name: pinot-wrapper
description: Wrapper chart for Pinot
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: pinot
    version: "~0.3.5"
    repository: https://raw.githubusercontent.com/apache/pinot/master/helm
