{{- if .Values.registerJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-express
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}
      
      containers:
      - name: register
        image: curlimages/curl:8.5.0
        command:
          - /bin/sh
          - -uc
          - |
            echo "Registering Mongo Express..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            echo "Sending registration request..."
            http_code=$(curl -sS -o /tmp/response.txt -w "%{http_code}" \
              -X POST "http://openframe-management.microservices.svc.cluster.local:8095/v1/tools/mongo-express" \
              -H "Content-Type: application/json" \
              --connect-timeout 5 \
              --max-time 20 \
              -d '{
                "tool": {
                  "id": "mongo-express",
                  "toolType": "MONGO_EXPRESS",
                  "name": "Mongo Express",
                  "description": "Mongo Express Web-based MongoDB Admin Interface",
                  "toolUrls": [
                    {
                      "url": "http://mongo-express.client-tools.svc.cluster.local",
                      "port": "80",
                      "type": "DASHBOARD"
                    }
                  ],
                  "category": "NoSQL Database",
                  "platformCategory": "OpenFrame Datasource",
                  "enabled": true,
                  "credentials": {},
                  "layer": "Datasource",
                  "layerOrder": 2,
                  "layerColor": "#4DB6AC",
                  "metricsPath": "/metrics",
                  "healthCheckEndpoint": "/",
                  "healthCheckInterval": 30,
                  "connectionTimeout": 5000,
                  "readTimeout": 5000,
                  "allowedEndpoints": ["/"],
                  "debeziumConnectors": []
                }
              }' \
              --retry 5 \
              --retry-delay 2 \
              --retry-all-errors)

            echo "----- Response body -----"
            cat /tmp/response.txt || true
            echo "-------------------------"

            [ -z "$http_code" ] || [ "$http_code" != 200 ] && { echo "Mongo Express Registration failed..."; exit 1; }
            echo "Mongo Express Registration complete."
{{- end }}
