apiVersion: v1
kind: ConfigMap
metadata:
  name: meshcentral-mongodb
data:
  MONGODB_HOST: "meshcentral-mongodb.integrated-tools.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGO_INITDB_DATABASE: "meshcentral"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: meshcentral-mongodb-init
data:
  mongo-init.sh: |-
{{ .Files.Get "scripts/meshcentral-mongodb-init.sh" | indent 4 }}
  mongodb-entrypoint.sh: |-
{{ .Files.Get "scripts/mongodb-entrypoint.sh" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: meshcentral-mongodb-readiness
data:
  readiness-command.sh: |-
{{ .Files.Get "scripts/meshcentral-readiness-command.sh" | indent 4 }}
