apiVersion: v1
kind: Secret
metadata:
  name: meshcentral-mongodb
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: K7vMzYZmkntu

---

apiVersion: v1
kind: Secret
metadata:
  name: meshcentral-mongodb-keyfile
type: Opaque
data:
  keyfile: a2srKzI4ZUZPWDZvaDFRY3lvcFNNVVBMMzNJMm1DaUc1NUNuOENzcytqOVphOC84cGFEbkFLRW0wQ0VmbnpsK3p4T3ROcWU5ZnBRSHVMWGt6K3ZZclpvZGJXczVZeHlTNUVIdnFVSzdzeG8xMzZ2c1g5dGxLWHdOK1h1OXg2ZVFoM3JIenlNdytyTlVhNmJhMEFsUmZ1aVBkNytYVmhtNkQ0cVFKSHMyaDVSaVVnNUNWS1RKaElST0pEd3RXNm5LNkZJMkhjZkowaVY3cmhTc0cxNnI1SFAvN3NIWHFOT3ZoVktpVUVxWk91bE8yWExXYmdTUjZmSGdzOHJsMmN4dFkzOUtjMkRESkNvbnZRZjN3RXdTS3ZpUXI5aWh3ODJuQW4rTXZOQUUwNjlJWTdHdzRwQWFjOFRrSmVqNjczUlN3YVh6UVBGVExNWXhxek9VV21HWmNQN2dqM2Y4dGhDblBMYXFMYnZOREJaUi96ZmkxeHRqQWM1TXU2bXF2U3pGVWpIbTdyeDM2Rzl5SzNsdTViSUQrKzJLSmo3V3pBcm9zOUd1NTRSZHdwV2VCV3NoV0Y5VUpHUUI3NElKejhuWThmaU9kSXFoYTNsQzBTUWllNEJEeEZqejh3djUrNkxmQUJKMHUyV1ZIVXE3dUxKczVqWUxONU1vR2l4MGF3VVQrTVB4NGM1ajU1K2E3Szk1RG5kZHF6cXJmYjhyNVF1YjRYeC9Fc01FLzVkb3l6bDFXR2VyVVNseG9OV1RCV1k0TUNiOUZSdUk5bEVEcWlBNjRoMUlNN2hNd0FmWGZVV3pyY0JlNFIwL25JcjlYS0hkRmhGY2ZRKzFVMEVBUmc1WXZzbnlEelNaT1R2TmFSS1JYdkNvL3FXRDBrZjdCSkNyNFJPMDVUMHdDTVNRcWNnc3ZKNXQwSXA4NU1xQlJEek02K0ZRNHIvT2haZDBvWlk4TGlJWjEzMW9Ya0w4V0poSTZWNmZoQnZieDN3R1V2TUY4cERLNVNJanhheFcyMHUzQ28rdkQ4Y29zMlYxRjNyTSsvZlNpMWR2WXpDRW03NG9uQ0lUTyt2VkxzMmFjajRYN2dybHduRmtjRDFZb1NOVlRFQXhpbHhZVVV6ak9vMGNIY252WjV5a1lzZnZDSjFxTm9Vbm9yTFYyc050TVFhd1hIWm1HNFU2aEpIeGpRUzdPR2pGNFoxcnpmSzNLTHpid2JXYmVUTGh6RUxMYmFVTDViZGlzQ0hzOW5RQ1NmQUNsT1E4eXcxMU5QV080VHl4aWNFeVo3Qml3RDUrc0NDbG5xTXpIS1dpZW56SVZZZGNlR3VkWnhMOWFTbGdCMWlJ