apiVersion: apps/v1
kind: Deployment
metadata:
  name: openframe-authorization-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openframe-authorization-server
  template:
    metadata:
      labels:
        app: openframe-authorization-server
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      initContainers:
        - name: wait-for-config-server
          image: {{ default .Values.initContainer.image.registry .Values.global.image.registry }}/curlimages/curl:{{ .Values.initContainer.image.tag }}
          command: ["sh", "-c", "until curl -f http://openframe-config.microservices.svc.cluster.local:8888/xml/shared-logback-spring.xml; do sleep 1; done"]

        - name: wait-for-management-server
          image: {{ default .Values.initContainer.image.registry .Values.global.image.registry }}/curlimages/curl:{{ .Values.initContainer.image.tag }}
          command: ["sh", "-c", "until curl -f http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do sleep 1; done"]
          
      containers:
        - name: openframe-authorization-server
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9005
              name: http
            - containerPort: 9006
              name: management
          env:
            {{- if and .Values.deployment.oss.enabled .Values.deployment.oss.ingress.ngrok.enabled }}
            - name: TENANT_HOST_URL
              value: {{ printf "https://%s" (required "deployment.oss.ingress.ngrok.url is required when ngrok ingress is enabled" .Values.deployment.oss.ingress.ngrok.url) | quote }}
            {{- else if or (and .Values.deployment.oss.enabled .Values.deployment.oss.ingress.localhost.enabled) (and .Values.deployment.saas.enabled .Values.deployment.saas.ingress.localhost.enabled) }}
            - name: TENANT_HOST_URL
              value: "https://localhost"
            {{- end }}
            - name: SPRING_CONFIG_URL
              value: "http://openframe-config.microservices.svc.cluster.local:8888"

          resources:
            {{- toYaml .Values.resources | nindent 10 }}

          livenessProbe:
            httpGet:
              path: /management/v1/health
              port: management
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /management/v1/health
              port: management
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
