{{- if .Values.global.registerJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: fleetmdm-redis
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}
      
      containers:
      - name: register
        image: curlimages/curl:8.5.0
        command:
          - /bin/sh
          - -uc
          - |
            echo "Registering FleetMDM Redis..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            echo "Sending registration request..."
            http_code=$(curl -sS -o /tmp/response.txt -w "%{http_code}" \
              -X POST "http://openframe-management.microservices.svc.cluster.local:8095/v1/tools/fleetmdm-redis" \
              -H "Content-Type: application/json" \
              --connect-timeout 5 \
              --max-time 20 \
              -d '{
                "tool": {
                  "id": "fleetmdm-redis",
                  "toolType": "REDIS",
                  "name": "FleetMDM Redis",
                  "description": "Redis Backend for FleetMDM",
                  "toolUrls": [
                    {
                      "url": "redis://fleetmdm-redis-0.fleetmdm-redis.integrated-tools.svc.cluster.local",
                      "port": "6379",
                      "type": "DATABASE"
                    }
                  ],
                  "category": "In-Memory Database",
                  "platformCategory": "Integrated Tool",
                  "enabled": true,
                  "credentials": {},
                  "layer": "Integrated Tools",
                  "layerOrder": 5,
                  "layerColor": "#B71C1C",
                  "metricsPath": "/metrics",
                  "healthCheckEndpoint": "/",
                  "healthCheckInterval": 30,
                  "connectionTimeout": 5000,
                  "readTimeout": 5000,
                  "allowedEndpoints": ["/metrics"],
                  "debeziumConnectors": []
                }
              }' \
              --retry 5 \
              --retry-delay 2 \
              --retry-all-errors)

            echo "----- Response body -----"
            cat /tmp/response.txt || true
            echo "-------------------------"

            [ -z "$http_code" ] || [ "$http_code" != 200 ] && { echo "FleetMDM Redis Registration failed..."; exit 1; }
            echo "FleetMDM Redis Registration complete."
{{- end }}