{{- if and .Values.deployment.saas.enabled .Values.deployment.saas.ingress.gcp.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openframe-frontend
spec:
  refreshInterval: "24h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-cluster-secret-store
  target:
    name: openframe-frontend
    creationPolicy: Owner
  data:
    - secretKey: NEXT_PUBLIC_GTM_CONTAINER_ID
      remoteRef:
        key: "{{ .Values.deployment.saas.ingress.gcp.externalSecretName }}"
        property: SAAS_TENANT.NEXT_PUBLIC_GTM_CONTAINER_ID

{{- end }}
