apiVersion: v2
name: cassandra-wrapper
description: Wrapper chart for Ð¡assandra
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: cassandra
    version: "~12.3.9"
    repository: oci://ghcr.io/flamingo-stack/registry/helm-charts
