
registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: curlimages/curl
    tag: "8.9.1"


redis:
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: redis
    tag: "7.4-alpine"