apiVersion: v2
name: grafana-wrapper
description: Wrapper chart for Grafana
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: grafana
    version: ">=9.2.10"
    repository: https://grafana.github.io/helm-charts
