apiVersion: v2
name: ngrok-operator-wrapper
description: Wrapper chart for Ngrok Operator
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: ngrok-operator
    version: ">=0.20.0"
    repository: https://charts.ngrok.com
