
registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: curlimages/curl
    tag: "8.9.1"


mysql:
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: mysql
    tag: "8.0.35"
