apiVersion: apps/v1
kind: Deployment
metadata:
  name: openframe-external-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openframe-external-api
  template:
    metadata:
      labels:
        app: openframe-external-api
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      initContainers:
        - name: wait-for-config-server
          image: {{ default .Values.initContainer.image.registry .Values.global.image.registry }}/curlimages/curl:{{ .Values.initContainer.image.tag }}
          command: ["sh", "-c", "until curl -f http://openframe-config.microservices.svc.cluster.local:8888/xml/shared-logback-spring.xml; do sleep 1; done"]

        - name: wait-for-management-server
          image: {{ default .Values.initContainer.image.registry .Values.global.image.registry }}/curlimages/curl:{{ .Values.initContainer.image.tag }}
          command: ["sh", "-c", "until curl -f http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do sleep 1; done"]
          
      containers:
        - name: openframe-external-api
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8092
              name: http
            - containerPort: 8093
              name: management
          env:
            - name: SPRING_CONFIG_URL
              value: "http://openframe-config.microservices.svc.cluster.local:8888"

          resources:
            {{- toYaml .Values.resources | nindent 10 }}

          livenessProbe:
            httpGet:
              path: /management/v1/health
              port: management
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /management/v1/health
              port: management
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
