apiVersion: v2
name: kube-prometheus-wrapper
description: Wrapper chart for Prometheus Community kube-prometheus-stack
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: kube-prometheus-stack
    version: ">=75.10.0"
    repository: https://prometheus-community.github.io/helm-charts
