{{- if .Values.registerJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: openframe-stream
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}
      
      containers:
      - name: register
        image: curlimages/curl:8.5.0
        command:
          - /bin/sh
          - -uc
          - |
            echo "Registering OpenFrame Stream..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            echo "Sending registration request..."
            http_code=$(curl -sS -o /tmp/response.txt -w "%{http_code}" \
              -X POST "http://openframe-management.microservices.svc.cluster.local:8095/v1/tools/openframe-stream" \
              -H "Content-Type: application/json" \
              --connect-timeout 5 \
              --max-time 20 \
              -d '{
                "tool": {
                  "id": "openframe-stream",
                  "toolType": "OPENFRAME",
                  "name": "OpenFrame Stream",
                  "description": "OpenFrame Stream Processing Service",
                  "toolUrls": [
                    {
                      "url": "http://openframe-stream.microservices.svc.cluster.local",
                      "port": "8091",
                      "type": "API"
                    }
                  ],
                  "category": "Stream Processing",
                  "platformCategory": "OpenFrame Core",
                  "enabled": true,
                  "credentials": {},
                  "layer": "Application",
                  "layerOrder": 4,
                  "layerColor": "#455A64",
                  "metricsPath": "/metrics",
                  "healthCheckEndpoint": "/health",
                  "healthCheckInterval": 30,
                  "connectionTimeout": 5000,
                  "readTimeout": 5000,
                  "allowedEndpoints": ["/api/v1/*", "/metrics"],
                  "debeziumConnectors": []
                }
              }' \
              --retry 5 \
              --retry-delay 2 \
              --retry-all-errors)

            echo "----- Response body -----"
            cat /tmp/response.txt || true
            echo "-------------------------"

            [ -z "$http_code" ] || [ "$http_code" != 200 ] && { echo "OpenFrame Stream Registration failed..."; exit 1; }
            echo "OpenFrame Stream Registration complete."
{{- end }}
