apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tactical-frontend
spec:
  serviceName: tactical-frontend
  replicas: 1
  selector:
    matchLabels:
      app: tactical-frontend
  template:
    metadata:
      labels:
        app: tactical-frontend
    spec:
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}

      containers:
      - name: tactical-frontend
        image: "{{ .Values.tactical.frontend.image.repo }}:{{ .Values.tactical.frontend.image.tag }}"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: tactical-default
        - configMapRef:
            name: tactical-postgres
        - configMapRef:
            name: tactical-redis
        - secretRef:
            name: tactical-postgres
        volumeMounts:
        - name: frontend-data
          mountPath: /opt/tactical
      volumes:
      - name: frontend-data
        persistentVolumeClaim:
          claimName: tactical-frontend
