apiVersion: v2
name: promtail-wrapper
description: Wrapper chart for Grafana Promtail
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: promtail
    version: ">=6.17.0"
    repository: https://grafana.github.io/helm-charts
