apiVersion: v1
kind: ConfigMap
metadata:
  name: debezium-connect-log4j
data:
  log4j.properties: |
    log4j.rootLogger=INFO, stdout

    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%t | %m | %c | %-5p%n

    log4j.logger.org.apache.zookeeper=WARN
    log4j.logger.org.apache.kafka=WARN
    log4j.logger.org.apache.kafka.connect=INFO
