deployment:
  saas:
    enabled: true
    ingress:
      localhost:
        enabled: false   
      gcp:
        enabled: true
        privateDomain: "internal.flamingo.cx"
        tenantID: "cluster-1001"

registry:
  docker:
    server: https://index.docker.io/v1/
    username: ""
    password: ""
    email: ""

global:
  image:
    tag: latest
