image:
  registry: ghcr.io/flamingo-stack/registry
  tag: "8.9.1"
    
deployment:
  saas:
    enabled: true
    ingress:
      localhost:
        enabled: false   
      gcp:
        enabled: true
        privateDomain: "internal.flamingo.cx"
        tenantID: "cluster-1001"

global:
  image:
    tag: latest
