apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
  annotations:
    "argocd.argoproj.io/sync-options": Replace=true
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: registration
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registration
    spec:
      restartPolicy: Always
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}

      containers:
      - name: register
        image: curlimages/curl:8.5.0
        command:
          - /bin/sh
          - -c
          - |
            echo "Registering Cluster..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            curl --verbose --show-error --fail \
              -X POST http://openframe-management.microservices.svc.cluster.local:8095/v1/cluster-registrations \
              -H "Content-Type: application/json" \
              -d '{
                  "imageTagVersion": "{{ .Values.global.image.tag }}"
              }' \
              --retry 20 \
              --retry-delay 15 \
              --retry-all-errors
            echo "Cluster Registration complete."
            echo "Keeping pod alive..."
            sleep infinity
