apiVersion: v1
kind: ConfigMap
metadata:
  name: meshcentral-server
data:
  MESH_DEVICE_GROUP: "OpenFrame"
  MESH_PORT: "8383"
  MESH_HOST: "0.0.0.0"
  MESH_EXTERNAL_HOST: "meshcentral-server-0.meshcentral-server.integrated-tools.svc.cluster.local"
  MESH_EXTERNAL_PORT: "8383"
  MESH_PERSISTENT_CONFIG: "0"
  MESH_DISABLE_SSL: "1"
  MESH_COMPRESSION_ENABLED: "true"
  MESH_WEBRTC_ENABLED: "false"
  MESH_TEMP_DIR: "/tmp/mesh"
  MESH_DIR: "/opt/mesh"
  MESH_PROTOCOL: "ws"
  MESH_NGINX_NAT_HOST: "meshcentral-server-0.meshcentral-server.integrated-tools.svc.cluster.local"
  MESH_NGINX_HOST: "meshcentral-server-0.meshcentral-server.integrated-tools.svc.cluster.local"
  MESH_NGINX_PORT: "80"
  OPENFRAME_MODE: "true"
