apiVersion: v2
name: redis-wrapper
description: Wrapper chart for Redis
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: redis
    version: "~23.2.6"
    repository: oci://ghcr.io/flamingo-stack/registry/helm-charts
