apiVersion: v2
name: mongodb-exporter-wrapper
description: Wrapper chart for Prometheus Mongodb Exporter
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: prometheus-mongodb-exporter
    version: ">=3.12.0"
    repository: https://prometheus-community.github.io/helm-charts
