apiVersion: v2
name: loki-wrapper
description: Wrapper chart for Grafana Loki
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: loki
    version: ">=6.43.0"
    repository: https://grafana.github.io/helm-charts
