apiVersion: v1
kind: ConfigMap
metadata:
  name: tactical-postgres
data:
  POSTGRES_DB: "tacticalrmm"
  POSTGRES_HOST: "tactical-postgres-0.tactical-postgres.integrated-tools.svc.cluster.local"
  POSTGRES_PORT: "5432"
  TEST: "TEST"
