apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-log4j2
data:
  log4j2.yaml: |
    Configuration:
      name: KafkaLog4j2Config

      Appenders:
        Console:
          name: STDOUT
          target: SYSTEM_OUT
          PatternLayout:
            pattern: "level=%p ts=%d{ISO8601} logger=%c thread=%t msg=\"%m\"%n"

      Loggers:
        Root:
          level: INFO
          AppenderRef:
            - ref: STDOUT
        Logger:
          - name: org.apache.zookeeper
            level: WARN
          - name: org.apache.kafka
            level: INFO
          - name: kafka
            level: INFO
          - name: kafka.controller
            level: INFO
          - name: state.change.logger
            level: INFO
