name: Generate Changes

on:
  workflow_call:
    outputs:      
      openframe-core: 
        value: ${{ jobs.changes.outputs.openframe-core }}
      openframe-data: 
        value: ${{ jobs.changes.outputs.openframe-data }}
      openframe-jwt: 
        value: ${{ jobs.changes.outputs.openframe-jwt }}
      api-library: 
        value: ${{ jobs.changes.outputs.api-library }}
      sdk-fleetmdm: 
        value: ${{ jobs.changes.outputs.sdk-fleetmdm }}
      openframe-api: 
        value: ${{ jobs.changes.outputs.openframe-api }}
      openframe-authorization-server: 
        value: ${{ jobs.changes.outputs.openframe-authorization-server }}
      openframe-external-api: 
        value: ${{ jobs.changes.outputs.openframe-external-api }}
      openframe-client: 
        value: ${{ jobs.changes.outputs.openframe-client }}
      openframe-config: 
        value: ${{ jobs.changes.outputs.openframe-config }}
      openframe-gateway: 
        value: ${{ jobs.changes.outputs.openframe-gateway }}
      openframe-management: 
        value: ${{ jobs.changes.outputs.openframe-management }}
      openframe-stream: 
        value: ${{ jobs.changes.outputs.openframe-stream }}
      openframe-ui: 
        value: ${{ jobs.changes.outputs.openframe-ui }}
      authentik-postgresql: 
        value: ${{ jobs.changes.outputs.authentik-postgresql }}
      fleetmdm: 
        value: ${{ jobs.changes.outputs.fleetmdm }}
      meshcentral: 
        value: ${{ jobs.changes.outputs.meshcentral }}
      tactical-frontend: 
        value: ${{ jobs.changes.outputs.tactical-frontend }}
      tactical-nginx: 
        value: ${{ jobs.changes.outputs.tactical-nginx }}
      tactical-base: 
        value: ${{ jobs.changes.outputs.tactical-base }}
      client: 
        value: ${{ jobs.changes.outputs.client }}
      timestamp: 
        value: ${{ jobs.changes.outputs.timestamp }}
      timestamp_tag: 
        value: ${{ jobs.changes.outputs.timestamp_tag }}
      commit_sha: 
        value: ${{ jobs.changes.outputs.commit_sha }}
      test_commit_sha: 
        value: ${{ jobs.changes.outputs.test_commit_sha }}

jobs:
  changes:
    name: Changes check
    runs-on: ubuntu-latest
    outputs:
      openframe-core: ${{ steps.filter.outputs.openframe-core }}
      openframe-data: ${{ steps.filter.outputs.openframe-data }}
      openframe-jwt: ${{ steps.filter.outputs.openframe-jwt }}
      api-library: ${{ steps.filter.outputs.api-library }}
      sdk-fleetmdm: ${{ steps.filter.outputs.sdk-fleetmdm }}
      openframe-api: ${{ steps.filter.outputs.openframe-api }}
      openframe-authorization-server: ${{ steps.filter.outputs.openframe-authorization-server }}
      openframe-external-api: ${{ steps.filter.outputs.openframe-external-api }}
      openframe-client: ${{ steps.filter.outputs.openframe-client }}
      openframe-config: ${{ steps.filter.outputs.openframe-config }}
      openframe-gateway: ${{ steps.filter.outputs.openframe-gateway }}
      openframe-management: ${{ steps.filter.outputs.openframe-management }}
      openframe-stream: ${{ steps.filter.outputs.openframe-stream }}
      openframe-ui: ${{ steps.filter.outputs.openframe-ui }}
      authentik-postgresql: ${{ steps.filter.outputs.authentik-postgresql }}
      fleetmdm: ${{ steps.filter.outputs.fleetmdm }}
      meshcentral: ${{ steps.filter.outputs.meshcentral }}
      tactical-frontend: ${{ steps.filter.outputs.tactical-frontend }}
      tactical-nginx: ${{ steps.filter.outputs.tactical-nginx }}
      tactical-base: ${{ steps.filter.outputs.tactical-base }}
      client: ${{ steps.filter.outputs.client }}
      timestamp: ${{ steps.setup_env.outputs.timestamp }}
      timestamp_tag: ${{ steps.setup_env.outputs.timestamp_tag }}
      commit_sha: ${{ steps.setup_env.outputs.commit_sha }}
      test_commit_sha: ${{ steps.setup_env.outputs.test_commit_sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up environment
        id: setup_env
        run: |
          echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
          echo "timestamp_tag=$(date +%d%m%Y%H%M)" >> $GITHUB_OUTPUT
          echo "commit_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          echo "test_commit_sha=test-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            client:
              - './client/**'
            openframe-core:
              - './pom.xml'
              - './openframe/libs/openframe-core/**'
            openframe-data:
              - './pom.xml'
              - './openframe/libs/openframe-data/**'
              - './openframe/libs/openframe-core/**'
            openframe-jwt:
              - './pom.xml'
              - './openframe/libs/openframe-jwt/**'
              - './openframe/libs/openframe-core/**'
            api-library:
              - './pom.xml'
              - './openframe/libs/api-library/**'
              - './openframe/libs/openframe-data/**'
              - './openframe/libs/openframe-core/**'
            sdk-fleetmdm:
              - './pom.xml'
              - './openframe/libs/sdk-fleetmdm/**'
            openframe-api:
              - './pom.xml'
              - './openframe/services/openframe-api/**'
              - './openframe/libs/api-library/**'
              - './openframe/libs/openframe-data/**'
              - './openframe/libs/openframe-jwt/**'
              - './openframe/libs/openframe-core/**'
            openframe-authorization-server:
              - './pom.xml'
              - './openframe/services/openframe-authorization-server/**'
              - './openframe/libs/openframe-jwt/**'
              - './openframe/libs/openframe-core/**'
            openframe-external-api:
              - './pom.xml'
              - './openframe/services/openframe-external-api/**'
              - './openframe/libs/api-library/**'
              - './openframe/libs/openframe-data/**'
              - './openframe/libs/openframe-core/**'
            openframe-client:
              - './pom.xml'
              - './openframe/services/openframe-client/**'
              - './openframe/libs/openframe-data/**'
              - './openframe/libs/openframe-jwt/**'
              - './openframe/libs/openframe-core/**'
            openframe-config:
              - './pom.xml'
              - './openframe/services/openframe-config/**'
            openframe-gateway:
              - './pom.xml'
              - './openframe/services/openframe-gateway/**'
              - './openframe/libs/openframe-jwt/**'
              - './openframe/libs/openframe-data/**'
              - './openframe/libs/openframe-core/**'
            openframe-management:
              - './pom.xml'
              - './openframe/services/openframe-management/**'
              - './openframe/libs/openframe-core/**'
              - './openframe/libs/openframe-data/**'
            openframe-stream:
              - './pom.xml'
              - './openframe/services/openframe-stream/**'
              - './openframe/libs/sdk-fleetmdm/**'
              - './openframe/libs/openframe-core/**'
              - './openframe/libs/openframe-data/**'
            openframe-ui:
              - './pom.xml'
              - './openframe/services/openframe-ui/**'
            authentik-postgresql:
              - './integrated-tools/authentik/postgresql/**'
            fleetmdm:
              - './integrated-tools/fleetmdm/**'
            meshcentral:
              - './integrated-tools/meshcentral/server/**'
            tactical-frontend:
              - './integrated-tools/tactical-rmm/tactical-frontend/**'
              - './integrated-tools/tactical-rmm/shared/**'
            tactical-nginx:
              - './integrated-tools/tactical-rmm/tactical-nginx/**'
              - './integrated-tools/tactical-rmm/shared/**'
            tactical-base:
              - './integrated-tools/tactical-rmm/tactical-base/**'
              - './integrated-tools/tactical-rmm/shared/**'
