name: Openframe Release Prod

# =============================================================================
# WORKFLOW CONFIGURATION
# =============================================================================

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

# =============================================================================
# JOBS
# =============================================================================

jobs:
  promote:
    name: "Create and Merge Release PR"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
      
      - name: Make Prod values changes
        env:
          VALUES_PATH: manifests/apps
        run: |
          cp ${VALUES_PATH}/values-stage.yaml ${VALUES_PATH}/values-prod.yaml
          sed -i "s/environment: stage/environment: prod/g" ${VALUES_PATH}/values-prod.yaml

      - name: Create Prod Release PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PR_TOKEN: ${{ secrets.PR_WRITE_ACCESS_TOKEN }}
        run: |
          git checkout -b release/prod-$(date +%Y-%m-%d-%H%M)
          git commit -am "Release Stage to Prod"
          git push -u origin HEAD --force
          PR_URL=$(gh pr create --draft --title "Openframe Release Prod (automatically generated PR)" --body "Update Prod with Stage values" --base main)
          GH_TOKEN=$GH_PR_TOKEN gh pr ready "${PR_URL}"  # to trigger the workflow
          GH_TOKEN=$GH_PR_TOKEN gh pr review "${PR_URL}" --approve
          gh pr merge "${PR_URL}" --squash --auto
